In [2]:
import pandas as pd
import os

In [24]:
os.listdir()

['train.csv',
 'pseudo_labeling.py',
 '.ipynb_checkpoints',
 'tta.py',
 'get_add_data.ipynb',
 'cassava-leaf-disease-classification',
 'cassava_optuna.ipynb',
 '.vscode',
 'train.py',
 'cassava-leaf-disease-classification.zip',
 'vit_cuda_as_usual_ensemble_inference(1).ipynb',
 'archive.zip',
 'add_data',
 'study.pkl',
 'apex',
 'cassava.ipynb',
 'utils',
 'train_cv7.csv',
 'train_stage_2.py']

In [30]:
data = pd.read_csv('train_cv7.csv',)

In [31]:
data.source[data.source == 'extra']

26337    extra
26338    extra
26339    extra
26340    extra
26341    extra
         ...
38927    extra
38928    extra
38929    extra
38930    extra
38931    extra
Name: source, Length: 12595, dtype: object

In [32]:
extra_files = os.listdir('/home/dmi/cassava/add_data/extraimages/extraimages/')
len(extra_files)

16370

In [33]:
new_data = data[data.source != 'extra'].append(pd.DataFrame({'image_id': extra_files, 'source': 'extra'}))
new_data

,Unnamed: 0,image_id,label,source,0,fold_0,fold_1,fold_2,fold_3,fold_4,fold_5,fold_6
0,0.0,1000015157.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,test,train,train,train,train
1,7.0,1001320321.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,train,train,test
2,18.0,1003888281.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,test,train,train
3,73.0,1012426959.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,test,train,train,train,train
4,109.0,1018973237.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,train,test,train
...,...,...,...,...,...,...,...,...,...,...,...,...
16365,NaN,extra-image-2287.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16366,NaN,extra-image-13726.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16367,NaN,extra-image-643.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16368,NaN,extra-image-4646.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16369,NaN,extra-image-4489.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
new_data[new_data.source == 'extra']

,Unnamed: 0,image_id,label,source,0,fold_0,fold_1,fold_2,fold_3,fold_4,fold_5,fold_6
0,NaN,extra-image-6798.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,extra-image-13522.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,test-img-297.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,extra-image-13188.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,extra-image-1739.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16365,NaN,extra-image-2287.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16366,NaN,extra-image-13726.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16367,NaN,extra-image-643.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16368,NaN,extra-image-4646.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16369,NaN,extra-image-4489.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
new_data.to_csv('train_cv7_add.csv')

In [37]:
new_data

,Unnamed: 0,image_id,label,source,0,fold_0,fold_1,fold_2,fold_3,fold_4,fold_5,fold_6
0,0.0,1000015157.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,test,train,train,train,train
1,7.0,1001320321.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,train,train,test
2,18.0,1003888281.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,test,train,train
3,73.0,1012426959.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,test,train,train,train,train
4,109.0,1018973237.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,train,test,train
...,...,...,...,...,...,...,...,...,...,...,...,...
16365,NaN,extra-image-2287.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16366,NaN,extra-image-13726.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16367,NaN,extra-image-643.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16368,NaN,extra-image-4646.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16369,NaN,extra-image-4489.jpg,NaN,extra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
data

,Unnamed: 0,image_id,label,source,0,fold_0,fold_1,fold_2,fold_3,fold_4,fold_5,fold_6
0,0,1000015157.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,test,train,train,train,train
1,7,1001320321.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,train,train,test
2,18,1003888281.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,test,train,train
3,73,1012426959.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,test,train,train,train,train
4,109,1018973237.jpg,0.0,2020,Cassava Bacterial Blight (CBB),train,train,train,train,train,test,train
...,...,...,...,...,...,...,...,...,...,...,...,...
38927,12590,extra-image-12848.jpg,NaN,extra,NaN,train,train,train,train,train,train,train
38928,12591,extra-image-2948.jpg,NaN,extra,NaN,train,train,train,train,train,train,train
38929,12592,extra-image-10040.jpg,NaN,extra,NaN,train,train,train,train,train,train,train
38930,12593,extra-image-13950.jpg,NaN,extra,NaN,train,train,train,train,train,train,train
38931,12594,extra-image-1058.jpg,NaN,extra,NaN,train,train,train,train,train,train,train